FROM openjdk:8-jdk-alpine
WORKDIR /home
COPY target/auth-manager-1.0-jar-with-dependencies.jar auth-manager-1.0-jar-with-dependencies.jar
CMD ["java", "-jar", "auth-manager-1.0-jar-with-dependencies.jar"]
